# -*- coding: utf-8 -*-
"""Comparer deux fichiers Excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvIIYRT6uk-ZPAsYPK9UUS1DiF-U3dJs
"""

import pandas as pd

"""# Comparaison de deux fichiers Excel

Ce programme compare 2 fichiers qui respectent le même formalisme, et dont il faut comparer les valeurs pour constater les évolutions entre le 2e (plus récent) et le premier.

Deux cas de figure sont traités :
1. quand les fichiers ont les mêmes en-têtes de colonne : par exemple le fichier 1 s'appelle **MonEntreprise2023.xlsx**, les 2 colonnes à comparer s'intitulent "Dépenses", "Recettes", et le 2e fichier s'appelle **MonEntreprise2024.xlsx** avec les mêmes colonnes
2. quand les fichiers ont des en-têtes différents : "2023" dans le 1er fichier, "2024" dans le second.

Dans les deux cas, le programme va chercher début de chaque ligne du fichier 2, et cherche l'équivalent dans la première colonne du fichier 1
"""

def filename2root(fname):
  return ".".join(fname.split(".")[:-1])

def compare_files_similar_headers(df1, df2, headers1, reportname):
  """
  Compare deux fichiers Excel (convertis en DataFrame) qui ont
  les mêmes en-têtes de colonnes
  """
  results = {h: [] for h in headers1}
  df2dict = df2.transpose().to_dict()
  df1dict = df1.transpose().to_dict()
  for entry in df2dict:
    comp = []
    for header in headers1:
      if entry in df1dict:
        old_val = df1dict[entry][header]
        new_val = df2dict[entry][header]
        if old_val != new_val:
          diff = new_val-old_val
          results[header].append(diff)
        else:
          results[header].append("")
      else:
        results[header].append("Ligne nouvelle")

  for header in headers1:
    new_h = f"Différence {header}"    
    df2[new_h] = results[header]

  df2.to_excel(reportname)

"""Exécution du code"""

fname1 = input("Nom du fichier 1 (le plus ancien) : ")
fname2 = input("Nom du fichier 2 (le plus récent) : ")
headers1 = input("Colonnes du fichier 1 à comparer (séparer par des virgules) : ")
headers2 = input("Colonnes du fichier 2 à comparer (laisser vides si identiques) : ")
reportname = f"Comparaison {filename2root(fname1)}-{filename2root(fname2)}.xlsx"



df1 = pd.read_excel(fname1, index_col=0)
df2 = pd.read_excel(fname2, index_col=0)

if headers2 == "":
  print("Cas 2 : les en-têtes de colonnes sont les mêmes")
  compare_files_similar_headers(df1, df2, headers1.split(","), reportname)

