# coding: utf-8

import re

from joblib import Parallel, delayed
import multiprocessing

import SRUextraction as sru

from stdf import *

NUM_PARALLEL = 10

errors_records = []

langues_label2code = {"abkhaze": "abk",
                    "acadien": "roa",
                    "aceh": "ace",
                    "achanti": "aka",
                    "achi": "myn",
                    "achinese": "ace",
                    "acholi": "ach",
                    "acoli": "ach",
                    "adagbe": "ada",
                    "adame": "ada",
                    "adan": "ada",
                    "adangme": "ada",
                    "adyghé": "ady",
                    "afar": "aar",
                    "afghan": "pus",
                    "afrihili": "afh",
                    "afrikaans": "afr",
                    "afro-asiatique": "afa",
                    "afro-asiatiques": "afa",
                    "aguacatec": "myn",
                    "aïnou": "ain",
                    "akan": "aka",
                    "akkadien": "akk",
                    "albanais": "alb",
                    "alémanique": "gsw",
                    "aléoute": "ale",
                    "algonkin": "oji",
                    "algonquine": "alg",
                    "algonquines": "alg",
                    "allemand": "ger",
                    "alsacien": "gsw",
                    "altaïque": "tut",
                    "altaïques": "tut",
                    "amharique": "amh",
                    "amorite": "sem",
                    "andalou": "spd",
                    "angika": "anp",
                    "anglais": "eng",
                    "anglo-normand": "roa",
                    "anglo-saxon": "ang",
                    "annamite": "vie",
                    "annobon": "cpp",
                    "anzanite": "elx",
                    "apabhramsa": "inc",
                    "apache": "apa",
                    "apaches": "apa",
                    "appa": "tiv",
                    "arabe": "ara",
                    "aragonais": "arg",
                    "arapaho": "arp",
                    "arawak": "arw",
                    "argobba": "sem",
                    "arménien": "arm",
                    "armoricain": "bre",
                    "aroumain": "rup",
                    "ashanti": "aka",
                    "assamais": "asm",
                    "assinibwan": "dak",
                    "assyro-babylonien": "akk",
                    "asturien": "ast",
                    "asturoléonais": "ast",
                    "athapascan": "den",
                    "athapascane": "ath",
                    "athapascanes": "ath",
                    "australienne": "aus",
                    "australiennes": "aus",
                    "austronésienne": "map",
                    "austronésiennes": "map",
                    "auvergnat": "oci",
                    "avar": "ava",
                    "avestique": "ave",
                    "awadhi": "awa",
                    "aymara": "aym",
                    "azerbaidjanais": "aze",
                    "azéri": "aze",
                    "aztec": "nah",
                    "aztèque": "nah",
                    "bable": "ast",
                    "babylonien": "akk",
                    "bachkir": "bak",
                    "bactrien": "ave",
                    "bagheli": "inc",
                    "bajjika": "inc",
                    "balinais": "ban",
                    "balkar": "krc",
                    "baloutchi": "bal",
                    "balte": "bat",
                    "baltes": "bat",
                    "bamana": "bam",
                    "bambara": "bam",
                    "bamiléké": "bai",
                    "banda": "bad",
                    "bandjalang": "aus",
                    "bangaru": "inc",
                    "baoulé": "nic",
                    "bartang": "ira",
                    "bas": "nds",
                    "basa": "bas",
                    "basaa": "bas",
                    "bashgali": "inc",
                    "baskir": "bak",
                    "basoutoland": "sot",
                    "basque": "baq",
                    "bassa": "bas",
                    "bas-sorabe": "dsb",
                    "batak": "btk",
                    "bavarois": "gsw",
                    "bèche-de-mer": "bis",
                    "bedja": "bej",
                    "beja": "bej",
                    "bella": "wak",
                    "bemba": "bem",
                    "bengali": "ben",
                    "béothuk": "nai",
                    "beraber": "ber",
                    "berbère": "ber",
                    "berbères": "ber",
                    "bété": "kro",
                    "bhili": "inc",
                    "bhojpuri": "bho",
                    "bichari": "bej",
                    "bichlamar": "bis",
                    "biélorusse": "bel",
                    "bihari": "bih",
                    "biharis": "bih",
                    "bikol": "bik",
                    "bilen": "byn",
                    "bilin": "byn",
                    "biloksi": "sio",
                    "biloxi": "sio",
                    "bini": "bin",
                    "birman": "bur",
                    "bislama": "bis",
                    "blackfoot": "bla",
                    "blin": "byn",
                    "Bliss": "zbl",
                    "bobo-oulé": "nic",
                    "bochiman": "khi",
                    "bokmål": "nob",
                    "bosniaque": "bos",
                    "boulouba-loulouwa": "lub",
                    "bouriate": "bua",
                    "bouthani": "dzo",
                    "brahui": "dra",
                    "braj": "bra",
                    "breton": "bre",
                    "bugi": "bug",
                    "bulgare": "bul",
                    "bundeli": "inc",
                    "buyi": "tai",
                    "byzantin": "grc",
                    "cachemirien": "kas",
                    "caddo": "cad",
                    "caffre": "xho",
                    "cajun": "roa",
                    "cakchikel": "myn",
                    "cambodgien": "khm",
                    "cananéen": "sem",
                    "canara": "kan",
                    "canarien": "ber",
                    "caraïbe": "car",
                    "carélien": "krl",
                    "carib": "car",
                    "carrier": "ath",
                    "castillan": "spa",
                    "catalan": "cat",
                    "caucasienne": "cau",
                    "caucasiennes": "cau",
                    "cayuga": "iro",
                    "cebuano": "ceb",
                    "celte": "cel",
                    "celtes": "cel",
                    "celtibère": "cel",
                    "celtique": "cel",
                    "celtiques": "cel",
                    "central": "khm",
                    "centrale": "cai",
                    "Centre": "mag",
                    "cewa": "nya",
                    "chabacano": "crp",
                    "chagataï": "chg",
                    "chakma": "inc",
                    "chaldéen": "arc",
                    "chame": "cmc",
                    "chames": "cmc",
                    "chamorro": "cha",
                    "chan": "shn",
                    "chanabal": "myn",
                    "chaoui": "ber",
                    "cherokee": "chr",
                    "chewa": "nya",
                    "cheyenne": "chy",
                    "chhattisgarhi": "inc",
                    "chibcha": "chb",
                    "chichewa": "nya",
                    "chichimeco": "oto",
                    "chilcotin": "ath",
                    "chimbundu": "kmb",
                    "chinois": "chi",
                    "chinook": "chn",
                    "chipewyan": "chp",
                    "chippewa": "oji",
                    "chiwere": "sio",
                    "chleuh": "ber",
                    "choctaw": "cho",
                    "cholti": "myn",
                    "chona": "sna",
                    "chorti": "myn",
                    "chuang": "zha",
                    "chuj": "myn",
                    "chung-chia": "tai",
                    "chuuk": "chk",
                    "cinghalais": "sin",
                    "cinuk": "chn",
                    "cinyanja": "nya",
                    "circassien": "cau",
                    "grec classique": "grc",
                    "colville": "sal",
                    "comorien": "bnt",
                    "comox": "sal",
                    "congo": "kon",
                    "coola": "sal",
                    "copte": "cop",
                    "coréen": "kor",
                    "cornique": "cor",
                    "cornouaillais": "bre",
                    "corse": "cos",
                    "corti": "myn",
                    "couchitique": "cus",
                    "couchitiques": "cus",
                    "creek": "mus",
                    "crimee": "crh",
                    "crioulo": "cpp",
                    "croate": "hrv",
                    "crow": "sio",
                    "cymraeg": "wel",
                    "d'": "oci",
                    "dai": "tai",
                    "dakota": "dak",
                    "d'Amérique": "bla",
                    "danois": "dan",
                    "dargwa": "dar",
                    "dari": "per",
                    "dayak": "day",
                    "delaware": "del",
                    "denka": "din",
                    "haïti": "hat",
                    "dhegiha": "sio",
                    "dimili": "zza",
                    "dimli": "zza",
                    "d'Inari": "smn",
                    "dinka": "din",
                    "dioula": "dyu",
                    "diour": "luo",
                    "divehi": "inc",
                    "djaghataï": "chg",
                    "djo": "ijo",
                    "djuka": "cpe",
                    "d'oc": "oci",
                    "dogri": "doi",
                    "dogrib": "dgr",
                    "dong": "tai",
                    "dongola-kenuz": "nub",
                    "douala": "dua",
                    "dravidienne": "dra",
                    "dravidiennes": "dra",
                    "dyirba": "aus",
                    "dyula": "dyu",
                    "dzongkha": "dzo",
                    "écossais": "sco",
                    "edo": "bin",
                    "efik": "efi",
                    "égyptien": "egy",
                    "ekajuk": "eka",
                    "élamite": "elx",
                    "erse": "gla",
                    "erza": "myv",
                    "espagnol": "spa",
                    "espagnols": "spd",
                    "espéranto": "epo",
                    "estonien": "est",
                    "euskara": "baq",
                    "euskera": "baq",
                    "éwé": "ewe",
                    "éwondo": "ewo",
                    "fanakalo": "crp",
                    "fang": "fan",
                    "fanti": "fat",
                    "farsi": "per",
                    "féroïen": "fao",
                    "fidjien": "fij",
                    "filipino": "fil",
                    "finlandais": "fin",
                    "finnois": "fin",
                    "finno-ougrienne": "fiu",
                    "finno-ougriennes": "fiu",
                    "flamand": "dut",
                    "flanc-de-chien": "dgr",
                    "flup": "dyu",
                    "fon": "fon",
                    "fox": "alg",
                    "français": "fre",
                    "francique": "gsw",
                    "frioulan": "fur",
                    "ful": "ful",
                    "fula": "ful",
                    "ga": "gaa",
                    "gadaba": "dra",
                    "gaélique": "gla",
                    "gagaouze": "tut",
                    "galibi": "car",
                    "galicien": "glg",
                    "galla": "orm",
                    "gallois": "wel",
                    "ganda": "lug",
                    "gang": "ach",
                    "garhwali": "inc",
                    "gascon": "oci",
                    "gaulois": "cel",
                    "gayo": "gay",
                    "gbaya": "gba",
                    "geez": "gez",
                    "ge'ez": "gez",
                    "gen": "ewe",
                    "géorgien": "geo",
                    "germanique": "gem",
                    "germaniques": "gem",
                    "ghaeilge": "gle",
                    "ghez": "gez",
                    "ghèze": "gez",
                    "gilaki": "ira",
                    "gilbert": "gil",
                    "gitan": "rom",
                    "godié": "kro",
                    "gond": "gon",
                    "gondi": "gon",
                    "gorontalo": "gor",
                    "gothique": "got",
                    "goudjrati": "guj",
                    "grebo": "grb",
                    "groenlandais": "kal",
                    "Guadeloupe": "cpf",
                    "guanche": "ber",
                    "guarani": "grn",
                    "guerze": "kpe",
                    "guèze": "gez",
                    "gujarati": "guj",
                    "gullah": "cpe",
                    "gurage": "sem",
                    "gurjari": "guj",
                    "gwich'in": "gwi",
                    "gypsy": "rom",
                    "haida": "hai",
                    "haisla": "wak",
                    "haïtien": "hat",
                    "halbi": "inc",
                    "haoussa": "hau",
                    "harari": "sem",
                    "hare": "ath",
                    "hatsa": "khi",
                    "hawaïen": "haw",
                    "hébreu": "heb",
                    "heiltsuk": "wak",
                    "hellénistique": "grc",
                    "herero": "her",
                    "hidatsa": "sio",
                    "hiligaynon": "hil",
                    "himachali": "him",
                    "himachalis": "him",
                    "hindi": "hin",
                    "hindki": "lah",
                    "hindoustani": "inc",
                    "hittite": "hit",
                    "hmong": "hmn",
                    "ho": "mun",
                    "hongrois": "hun",
                    "hottentot": "khi",
                    "huastec": "myn",
                    "hupa": "hup",
                    "iai": "map",
                    "iakota": "dak",
                    "iakoute": "sah",
                    "iban": "iba",
                    "ibidio": "efi",
                    "ibo": "ibo",
                    "ido": "ido",
                    "igbo": "ibo",
                    "ijo": "ijo",
                    "ilocano": "ilo",
                    "indonesia": "ind",
                    "indonésien": "ind",
                    "ingouche": "inh",
                    "inuktituk": "iku",
                    "inupiaq": "ipk",
                    "irakou": "cus",
                    "irakw": "cus",
                    "iranien": "per",
                    "iranienne": "ira",
                    "iraniennes": "ira",
                    "irlandais": "gle",
                    "iroquois": "iro",
                    "iroquoise": "iro",
                    "iroquoises": "iro",
                    "isiswazy": "ssw",
                    "isixhosa": "xho",
                    "islandais": "ice",
                    "italien": "ita",
                    "italiens": "itd",
                    "ixil": "myn",
                    "jacalteca": "myn",
                    "japonais": "jpn",
                    "jargon": "chn",
                    "javanais": "jav",
                    "jingpho": "kac",
                    "judéo-allemand": "yid",
                    "judéo-arabe": "jrb",
                    "judéo-espagnol": "lad",
                    "judéo-persan": "jpr",
                    "judesmo": "lad",
                    "kabardien": "kbd",
                    "kabyle": "kab",
                    "kachin": "kac",
                    "kachoube": "csb",
                    "kaçmiri": "kas",
                    "kafir": "ine",
                    "kalaallisut": "kal",
                    "kalispel": "sal",
                    "kalmouk": "xal",
                    "kamba": "kam",
                    "kanara": "kan",
                    "kanjobal": "myn",
                    "kannada": "kan",
                    "kannara": "kan",
                    "kanouri": "kau",
                    "karakalpak": "kaa",
                    "karanda": "bnt",
                    "karen": "kar",
                    "karib": "car",
                    "karo": "vai",
                    "kashmiri": "kas",
                    "kaska": "ath",
                    "kasmiri": "kas",
                    "kawchoddine": "ath",
                    "kawi": "kaw",
                    "kazakh": "kaz",
                    "kekchi": "myn",
                    "kekci": "myn",
                    "kharia": "mun",
                    "khasi": "kha",
                    "khoïsan": "khi",
                    "khorezmi": "ira",
                    "khotanais": "kho",
                    "khouzien": "elx",
                    "khowar": "inc",
                    "kice": "myn",
                    "kickapoo": "alg",
                    "kicua": "que",
                    "kikuyu": "kik",
                    "kimbundu": "kmb",
                    "kinyarwanda": "kin",
                    "kiowa-apache": "ath",
                    "kirdki": "zza",
                    "kirghiz": "kir",
                    "kiribati": "gil",
                    "kirmanjki": "zza",
                    "kiroundi": "run",
                    "kirundi": "run",
                    "kiwai": "paa",
                    "klingon": "tlh",
                    "kodagu": "dra",
                    "koko": "bas",
                    "kolami": "dra",
                    "kom": "kom",
                    "kongo": "kon",
                    "konkani": "kok",
                    "kootenai": "kut",
                    "korwa": "mun",
                    "kosrae": "kos",
                    "kota": "dra",
                    "koumyk": "kum",
                    "kourkou": "mun",
                    "koutchéen": "ine",
                    "koyukon": "ath",
                    "kpele": "kpe",
                    "kpellé": "kpe",
                    "krio": "cpe",
                    "kriol": "cpe",
                    "krou": "kro",
                    "kru": "kro",
                    "kuanyama": "kua",
                    "kui": "dra",
                    "kuitsch": "ath",
                    "kumauni": "inc",
                    "kurde": "kur",
                    "kurmali": "inc",
                    "kurukh": "kru",
                    "kutchin": "ath",
                    "kutenai": "kut",
                    "kuvi": "dra",
                    "kwakiutl": "wak",
                    "kwanyama": "kua",
                    "ladin": "roh",
                    "ladino": "lad",
                    "lahnda": "lah",
                    "lak": "cau",
                    "lamba": "lam",
                    "lambadi": "inc",
                    "lampong": "map",
                    "lanatai": "tai",
                    "landsmål": "nno",
                    "languedocien": "oci",
                    "lao": "lao",
                    "laotien": "lao",
                    "lapon": "smi",
                    "latin": "lat",
                    "latvien": "lav",
                    "léonais": "ast",
                    "léonard": "bre",
                    "lette": "lav",
                    "letton": "lav",
                    "lezghien": "lez",
                    "Liberia": "kro",
                    "libyque": "ber",
                    "lillooet": "sal",
                    "limbourgeois": "lim",
                    "limousin": "oci",
                    "lingala": "lin",
                    "linguistique": "zxx",
                    "lituanien": "lit",
                    "liturgique": "chu",
                    "live": "fiu",
                    "livonien": "fiu",
                    "lojban": "jbo",
                    "lolo": "lol",
                    "lori": "ira",
                    "louba": "lub",
                    "louganda": "lug",
                    "Lowlands": "sco",
                    "lozi": "loz",
                    "katanga": "lub",
                    "lulua": "lua",
                    "luiseno": "lui",
                    "Lule": "smj",
                    "lunda": "lun",
                    "luo": "luo",
                    "lushai": "lus",
                    "luwi": "ine",
                    "luxembourgeois": "ltz",
                    "macaronique": "art",
                    "macédonien": "mac",
                    "madourais": "mad",
                    "magahi": "mag",
                    "magyar": "hun",
                    "fiyadikka": "nub",
                    "mahican": "alg",
                    "maithili": "mai",
                    "makassar": "mak",
                    "malais": "may",
                    "malayalam": "mal",
                    "maldivien": "div",
                    "malecite": "alg",
                    "malgache": "mlg",
                    "malinké": "man",
                    "mallorquin": "cad",
                    "maltais": "mlt",
                    "malto": "dra",
                    "mam": "myn",
                    "mandaite": "sem",
                    "mandan": "sio",
                    "mandar": "mdr",
                    "mandchou": "mnc",
                    "mandé": "man",
                    "mandéen": "sem",
                    "mandingue": "man",
                    "manipuri": "mni",
                    "mannois": "glv",
                    "manobo": "mno",
                    "manx": "glv",
                    "maori": "mao",
                    "mapuce": "arn",
                    "mapuche": "arn",
                    "mapudungun": "arn",
                    "marathe": "mar",
                    "marathi": "mar",
                    "mari": "chm",
                    "marshall": "mah",
                    "Martinique": "cpf",
                    "marvari": "mwr",
                    "masai": "mas",
                    "massachuset": "alg",
                    "massaï": "mas",
                    "matlalzinca": "oto",
                    "Maurice": "cpf",
                    "maya": "myn",
                    "mazahui": "oto",
                    "mbundu": "umb",
                    "mean-ghaeilge": "mga",
                    "meithei": "mni",
                    "mendé": "men",
                    "mengo": "lol",
                    "menomini": "alg",
                    "messapien": "ine",
                    "micmac": "mic",
                    "milanais": "itd",
                    "mina": "ewe",
                    "minangkabao": "min",
                    "minangkabau": "min",
                    "mirandais": "mwl",
                    "mocho": "myn",
                    "grec moderne": "gre",
                    "mohawk": "moh",
                    "mohegan": "alg",
                    "moksa": "mdf",
                    "moldave": "rum",
                    "mongo": "lol",
                    "mongol": "mon",
                    "môn-khmer": "mkh",
                    "montagnais": "cre",
                    "mopan": "myn",
                    "moré": "mos",
                    "mossi": "mos",
                    "motu": "hmo",
                    "mounchi": "tiv",
                    "mounda": "mun",
                    "moundari": "mun",
                    "mozabite": "ber",
                    "multilingue": "mul",
                    "multiples": "mmm",
                    "muskogee": "mus",
                    "mvele": "bas",
                    "myang": "tai",
                    "nahali": "mun",
                    "nahua": "nah",
                    "nahuatl": "nah",
                    "nandi": "ssa",
                    "nano": "umb",
                    "napolitain": "nap",
                    "naskapi": "cre",
                    "nauruan": "nau",
                    "navaho": "nav",
                    "naxi": "sit",
                    "ndonga": "ndo",
                    "néerlandais": "dut",
                    "néo-syriaque": "syr",
                    "népalais": "nep",
                    "nevari": "new",
                    "newari": "new",
                    "nguna": "map",
                    "nias": "nia",
                    "nigéro-congolaises": "nic",
                    "nigéro-kordofanienne": "nic",
                    "nigéro-kordofaniennes": "nic",
                    "nilo-saharienne": "ssa",
                    "nilo-sahariennes": "ssa",
                    "nitinat": "wak",
                    "niué": "niu",
                    "niuean": "niu",
                    "n'ko": "nqo",
                    "nkoré": "nyn",
                    "nogaï": "nog",
                    "nogay": "nog",
                    "nookta": "wak",
                    "nord-amérindiennes": "nai",
                    "norrois": "non",
                    "norvégien": "nor",
                    "ntlakyapamuk": "sal",
                    "nubien": "nub",
                    "nubienne": "nub",
                    "nubiennes": "nub",
                    "nyamwezi": "nym",
                    "nyanja": "nya",
                    "nyankolé": "nyn",
                    "Nyasa": "tog",
                    "nynorsk": "nno",
                    "nyoro": "nyo",
                    "nzema": "nzi",
                    "nzima": "nzi",
                    "oc": "oci",
                    "occitan": "oci",
                    "ocuilteco": "oto",
                    "ofogoula": "sio",
                    "oïrat": "xal",
                    "ojibwa": "oji",
                    "okanagon": "sal",
                    "omaha": "sio",
                    "oneida": "iro",
                    "onondaga": "iro",
                    "oriya": "ori",
                    "oromo": "orm",
                    "oroqen": "tut",
                    "osage": "osa",
                    "osmanli": "ota",
                    "ossète": "oss",
                    "ostiak": "sel",
                    "oto": "sio",
                    "otomi": "oto",
                    "ottawa": "oji",
                    "ottoman": "ota",
                    "oualof": "wol",
                    "oubykh": "cau",
                    "oudmourte": "udm",
                    "ougaritique": "uga",
                    "ouïgour": "uig",
                    "ouolof": "wol",
                    "ourdou": "urd",
                    "ouszbek": "uzb",
                    "pachto": "pus",
                    "pachtou": "pus",
                    "pahlavi": "pal",
                    "pahouin": "fan",
                    "palanquero": "crp",
                    "palau": "pau",
                    "palauan": "pau",
                    "Palenque": "crp",
                    "paléoslave": "sla",
                    "pali": "pli",
                    "pame": "oto",
                    "pampangan": "pam",
                    "pangasinan": "pag",
                    "panjabi": "pan",
                    "papiamento": "pap",
                    "papoue": "paa",
                    "papoues": "paa",
                    "passamaquoddy": "alg",
                    "pedi": "nso",
                    "pendjabi": "pan",
                    "pengo": "dra",
                    "penobscot": "alg",
                    "persan": "per",
                    "peul": "ful",
                    "phénicien": "phn",
                    "phiap": "tai",
                    "philippine": "phi",
                    "philippines": "phi",
                    "pidgin": "crp",
                    "pidgins": "crp",
                    "pilipino": "fil",
                    "pisin": "tpi",
                    "pohnpei": "pon",
                    "pokoman": "myn",
                    "pokonchi": "myn",
                    "polabe": "sla",
                    "polonais": "pol",
                    "polyglotte": "mul",
                    "polytonique": "grp",
                    "portugais": "por",
                    "pouchtou": "pus",
                    "prâkrit": "pra",
                    "précisé": "crp",
                    "provençal": "oci",
                    "pular": "ful",
                    "punique": "sem",
                    "punjabi": "pan",
                    "quechua": "que",
                    "quercinol": "oci",
                    "quiché": "myn",
                    "quichua": "que",
                    "quinault": "sal",
                    "rajasthani": "raj",
                    "rajputani": "inc",
                    "rapanui": "rap",
                    "rarotonga": "rar",
                    "Réunion": "cpf",
                    "rhéto-roman": "roh",
                    "rifain": "ber",
                    "romanche": "roh",
                    "romane": "roa",
                    "romanes": "roa",
                    "romani": "rom",
                    "rouergat": "oci",
                    "roumain": "rum",
                    "rundi": "run",
                    "russe": "rus",
                    "rusyn": "sla",
                    "ruthène": "sla",
                    "rwanda": "kin",
                    "sabéen": "sem",
                    "Saint-Domingue": "cpf",
                    "Saint-Lucie": "cpf",
                    "saka": "kho",
                    "sakan": "kho",
                    "sakha": "sah",
                    "salish": "sal",
                    "salishenne": "sal",
                    "salishennes": "sal",
                    "samaritain": "sam",
                    "same": "smi",
                    "sames": "smi",
                    "samoan": "smo",
                    "sandawe": "sad",
                    "sango": "sag",
                    "sanskrit": "san",
                    "santal": "sat",
                    "santali": "mun",
                    "santee": "dak",
                    "sarakollé": "man",
                    "saramaccan": "cpe",
                    "sarde": "srd",
                    "sarsi": "ath",
                    "sasak": "sas",
                    "scheshelt": "sal",
                    "sean-ghaeilge": "sga",
                    "sekani-beaver": "ath",
                    "selkoupe": "sel",
                    "sémitique": "sem",
                    "sémitiques": "sem",
                    "seneca": "iro",
                    "sepedi": "nso",
                    "septentrional": "frr",
                    "serbe": "srp",
                    "serer": "srr",
                    "sérère": "srr",
                    "sesotho": "sot",
                    "sesoutho": "sot",
                    "setchwana": "tsn",
                    "Seychelles": "cpf",
                    "shawnee": "alg",
                    "shilha": "ber",
                    "shina": "inc",
                    "shona": "sna",
                    "shqip": "alb",
                    "shughni": "ira",
                    "shuswap": "sal",
                    "siamois": "tha",
                    "Sichuan": "iii",
                    "sicilien": "scn",
                    "sidamo": "sid",
                    "signes": "sgn",
                    "siksika": "bla",
                    "sindhi": "snd",
                    "singhalais": "sin",
                    "sino-tibétaine": "sit",
                    "sino-tibétaines": "sit",
                    "sisien": "elx",
                    "siswati": "ssw",
                    "skolt": "sms",
                    "slave": "sla",
                    "slaves": "sla",
                    "slovaque": "slo",
                    "slovène": "slv",
                    "sogdien": "sog",
                    "somali": "som",
                    "songhai": "son",
                    "soninké": "snk",
                    "sorabe": "hsb",
                    "sorabes": "wen",
                    "soso": "sus",
                    "souabe": "gsw",
                    "souahéli": "swa",
                    "soundanais": "sun",
                    "soussou": "sus",
                    "squamish": "sal",
                    "squawmish": "sal",
                    "stalo": "sal",
                    "sub-saharienne": "ssa",
                    "sub-sahariennes": "ssa",
                    "sud-amérindiennes": "sai",
                    "suédois": "swe",
                    "sukuma": "suk",
                    "sumérien": "sux",
                    "sundanese": "sun",
                    "suomi": "fin",
                    "susien": "elx",
                    "susique": "elx",
                    "susu": "sus",
                    "swahili": "swa",
                    "swati": "ssw",
                    "syriaque": "syr",
                    "Tabasco": "myn",
                    "tachelhit": "ber",
                    "tadjik": "tgk",
                    "tagal": "tgl",
                    "tagalog": "tgl",
                    "tagish": "ath",
                    "tahitien": "tah",
                    "tahltan": "ath",
                    "tai": "tai",
                    "takulli": "ath",
                    "talysh": "ira",
                    "tamacheq": "tmh",
                    "tamazight": "ber",
                    "tamil": "tam",
                    "tamoul": "tam",
                    "tanaina": "ath",
                    "tanana": "ath",
                    "tangoute": "sit",
                    "tangut": "sit",
                    "Tanzanie": "luo",
                    "taqbaylit": "kab",
                    "tarifit": "ber",
                    "tatar": "tat",
                    "tchagataï": "chg",
                    "tchèque": "cze",
                    "tchétchène": "che",
                    "tchi": "twi",
                    "tchinuk": "chn",
                    "tchi-tonga": "tog",
                    "tchlingchadinne": "dgr",
                    "tchouvache": "chv",
                    "télinga": "tel",
                    "télougou": "tel",
                    "télugu": "tel",
                    "témène": "tem",
                    "temne": "tem",
                    "terena": "ter",
                    "tereno": "ter",
                    "teton": "dak",
                    "tetum": "tet",
                    "thaï": "tha",
                    "thlingchadinne": "ath",
                    "thompson": "sal",
                    "tibétain": "tib",
                    "tigré": "tig",
                    "tigrigna": "tir",
                    "tigrinya": "tir",
                    "timné": "tem",
                    "tiv": "tiv",
                    "tiwi": "aus",
                    "tlingit": "tli",
                    "toda": "dra",
                    "tokelau": "tkl",
                    "tokharien": "ine",
                    "tonga": "tog",
                    "tongo": "srn",
                    "touareg": "tmh",
                    "toucouleur": "ful",
                    "touva": "tyv",
                    "trégorois": "bre",
                    "truk": "chk",
                    "tsattine": "ath",
                    "tsigane": "rom",
                    "tsilkoltin": "ath",
                    "tsimchiane": "tsi",
                    "tsimshian": "tsi",
                    "tsonga": "tso",
                    "tswana": "tsn",
                    "tukkuthkutchin": "ath",
                    "tulu": "dra",
                    "tumbuka": "tum",
                    "tupi": "tup",
                    "turc": "tur",
                    "turcoman": "tuk",
                    "turco-tatar": "crh",
                    "turkmène": "tuk",
                    "turquien": "ota",
                    "tuscarora": "iro",
                    "tutelo": "sio",
                    "tuvalu": "tvl",
                    "twi": "twi",
                    "tzeltal": "myn",
                    "tzigane": "rom",
                    "tzotzil": "myn",
                    "tzutuhil": "myn",
                    "ud-murt": "udm",
                    "ugaritique": "uga",
                    "ukrainien": "ukr",
                    "umbundu": "umb",
                    "umpqua": "ath",
                    "upper": "ath",
                    "urdu": "urd",
                    "uspanteca": "myn",
                    "uzbek": "uzb",
                    "vaï": "vai",
                    "valencien": "cat",
                    "valentien": "cad",
                    "vannetais": "bre",
                    "veddah": "inc",
                    "védique": "san",
                    "venda": "ven",
                    "vénitien": "itd",
                    "vets": "fiu",
                    "vey": "vai",
                    "vivaro-alpin": "oci",
                    "volapük": "vol",
                    "vote": "vot",
                    "votiak": "udm",
                    "wailbri": "aus",
                    "wakashane": "wak",
                    "wakashanes": "wak",
                    "walamo": "wal",
                    "wallon": "wln",
                    "wampanoag": "alg",
                    "waray": "war",
                    "washo": "was",
                    "wende": "wen",
                    "winnebago": "sio",
                    "wolaitta": "wal",
                    "wolaytta": "wal",
                    "wolof": "wol",
                    "wotapuri-katarqalai": "inc",
                    "xhosa": "xho",
                    "xixia": "sit",
                    "yagaryagar": "aus",
                    "yakoute": "sah",
                    "yangton": "dak",
                    "yao": "yao",
                    "yap": "yap",
                    "yapois": "yap",
                    "yiddish": "yid",
                    "yoruba": "yor",
                    "yuan": "tai",
                    "yupik": "ypk",
                    "zan": "cau",
                    "zandé": "znd",
                    "zapotèque": "zap",
                    "zaza": "zza",
                    "zazaki": "zza",
                    "zenaga": "zen",
                    "zend": "ave",
                    "zhuang": "zha",
                    "zoulou": "zul",
                    "zuni": "zun"
            }



reg_lang = f"(trad\.|traduit|traduction|translated) (de l'|du |de la langue |from )({'|'.join(list(langues_label2code.keys()))})"


def launch_query(query, param_debut, param_fin, report):
    #first_result = sru.SRU_result(query, "http://catalogueservice.bnf.fr/SRU", {"recordSchema": "InterXMarc_Complet", "maximumRecords": "1"})
    first_result = sru.SRU_result(query, parametres={"recordSchema": "intermarcxchange", "maximumRecords": "1"})
    print(first_result.url)
    nb_results = first_result.nb_results
    
    if param_fin > nb_results:
        param_fin = nb_results
    
    params = {"recordSchema": "intermarcxchange", "maximumRecords": "500"}
    startRecord_list = [str(i) for i in range(param_debut, param_fin, 500)]
    #print(startRecord_list)
    i = 1
    for sublist in chunks(startRecord_list, NUM_PARALLEL):
        print(sublist[0])
        results = Parallel(n_jobs=NUM_PARALLEL)(delayed(launch_1sru_query)(query, startRecord, params) for startRecord in sublist)
        for results_page in results:
            for metas in results_page:
                line2report(metas, report, display=False)
                i += 1



def chunks(lst, n):
    """
    Permet de découper les requêtes dans le SRU par 10.000 (donc de paralléliser 
    10 requêtes de 1000"""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]



def launch_1sru_query(query, startRecord, params):
    params["startRecord"] = startRecord
    results = sru.SRU_result(query, parametres=params)
    list_results = []
    for ark in results.dict_records:
        list_results.append(analyse_record(ark, results.dict_records[ark]))
    list_results = [el for el in list_results if el]
    return list_results


def analyse_record(ark, xml_record):
    metas = []
    f041 = sru.record2fieldvalue(xml_record, "041")
    if f041 == "":
        f008 = sru.record2fieldvalue(xml_record, "008")[31:34]
        f142 = sru.record2fieldvalue(xml_record, "142")
        f245 = sru.record2fieldvalue(xml_record, "245")
        f917 = sru.record2fieldvalue(xml_record, "917")
        cri = ["", "oui"]["CRI" in f917]
        resp = get_resp(ark, xml_record)
        case, str_founded, f041 = analyse_case(xml_record, f008, f142, f245, resp)
        doctype = ""
        if xml_record is not None:
            doctype = sru.Record2metas(ark, xml_record, "").docrecordtype
        metas.append("\t".join([ark, 
                                ark2nn(ark),
                                doctype,
                                f008, f142, f245, resp,
                                f917,
                                cri,
                                case,
                                str_founded,
                                f041]))
    return metas

def analyse_case(xml_record, f008, f142, f245, resp):
    # Si la notice n'a pas de 041, on regarde ce qu'il y a dedans
    case = []
    str_founded = ""
    f041 = ""
    f008_val_pb = ["mul", "mmm", "   ", "...", "und", "###"]
    if f008 in f008_val_pb:
        case.append(f"Zone 008 {f008}")
    if f142:
        case.append("Présence d'une zone 142")
    if "$4 0680" in resp:
        case.append("Mention d'un traducteur")
    test_tit = re.search(reg_lang, f245.lower())
    if test_tit is not None:
        case.append(f"Mention d'une traduction en 245")
        str_founded = test_tit[0]
    if f008 not in f008_val_pb and test_tit is None:
        f041 = f"041 $ a {f008}"
    elif f008 not in f008_val_pb and test_tit is not None:
        f041 = f"041 $a {f008} $c {langues_label2code[test_tit.group(3)]}"
    return ", ".join(case), str_founded, f041


def get_resp(ark, xml_record):
    # récupération des mentions de responsabilité
    fields = "100,101,102,110,111,112,700,701,702,710,711,712".split(",")
    fields_values = []
    try:
        for field in fields:
            for f_occ in xml_record.xpath(f"*[@tag='{field}']"):
                value = sru.field2value(f_occ)
                fields_values.append(f"{field} {value}")
    except AttributeError as err:
        #errors_records.append([ark, field, "AttributeError", str(err)])
        pass
    fields_values = "¤".join(fields_values)
    return fields_values


if __name__ == "__main__":
    query = 'bib.anywhere all "-*-" and bib.doctype all "a" and bib.recordtype all "MON"'
    #query = 'Date any "1* 2* 3* 4* 5* 6* 7* 8* 9* 0*"'
    param_debut = int(input("Nombre début : "))
    param_fin = param_debut + 5000000
    #param_fin = param_debut + 10000
    report = create_file(f"NNB_sans_041-{str(param_debut)}.txt", "ARK,NNB,Type,008[langue],142,245,Responsabilités,9XX,CRI ?,Cas,Chaîne de caractères trouvée,041".split(","))
    launch_query(query, param_debut, param_fin, report)
    if errors_records:
        errors_file = create_file(f"NNB_sans_041-{str(param_debut)}-errors.txt")
        for error in errors_records:
            line2report(error, errors_file)